env:
  jest/globals: true
  browser: false
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules:
  semi: 0
  implicit-arrow-linebreak: ['error', 'below']
plugins:
  - jest
