version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    docker:
      - image: renatoargh/circleci-node-awscli
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn lint
            - run: yarn test
workflows:
  test:
    jobs:
      - test
